"""empty message

Revision ID: 491258e978be
Revises: d1f043f9e06d
Create Date: 2025-03-29 18:06:10.379243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491258e978be'
down_revision: Union[str, None] = 'd1f043f9e06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkspace', sa.Column('booker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parkspace', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'parkspace', 'user', ['booker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parkspace', type_='foreignkey')
    op.drop_constraint(None, 'parkspace', type_='foreignkey')
    op.drop_column('parkspace', 'booker_id')
    # ### end Alembic commands ###
