"""empty message

Revision ID: 5fb58a57be6a
Revises: 89e4ee8dcfe2
Create Date: 2025-03-29 21:19:02.350981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb58a57be6a'
down_revision: Union[str, None] = '89e4ee8dcfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance')
    op.drop_column('booking', 'price')
    # ### end Alembic commands ###
