"""empty message

Revision ID: 6e6bf1aba16a
Revises: 491258e978be
Create Date: 2025-03-29 20:08:24.139511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6bf1aba16a'
down_revision: Union[str, None] = '491258e978be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('parking_space_id', sa.Integer(), nullable=False),
    sa.Column('booker_id', sa.Integer(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['booker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parkspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('parkspace_booker_id_fkey', 'parkspace', type_='foreignkey')
    op.drop_column('parkspace', 'booker_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkspace', sa.Column('booker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parkspace_booker_id_fkey', 'parkspace', 'user', ['booker_id'], ['id'])
    op.drop_table('booking')
    # ### end Alembic commands ###
