"""empty message

Revision ID: 72edbb008a1a
Revises: b1776e3bb818
Create Date: 2025-03-29 12:00:17.629256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72edbb008a1a'
down_revision: Union[str, None] = 'b1776e3bb818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('parkspace', sa.Column('owner_id', sa.Integer(), nullable=False, default=0))
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=False, server_default='a'))
    op.add_column('user', sa.Column('car_number', sa.String(), nullable=False, server_default='a'))
    op.create_unique_constraint(None, 'user', ['car_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'car_number')
    op.drop_column('user', 'password_hash')
    #op.drop_column('parkspace', 'owner_id')
    # ### end Alembic commands ###
