"""empty message

Revision ID: 89e4ee8dcfe2
Revises: 6e6bf1aba16a
Create Date: 2025-03-29 20:48:18.923405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e4ee8dcfe2'
down_revision: Union[str, None] = '6e6bf1aba16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('_type', sa.String(), server_default='BOOKING', nullable=False))
    op.add_column('booking', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.alter_column('booking', 'booker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('booking', 'end_at')
    op.drop_column('booking', 'start_at')
    op.drop_column('booking', '_type')
    # ### end Alembic commands ###
